# Generated by Django 2.1 on 2019-02-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('major_name', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tuition_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('state_code', models.IntegerField(blank=True, null=True)),
                ('url_now', models.CharField(blank=True, max_length=255, null=True)),
                ('url_old', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitor',
                'managed': True,
            },
        ),
    ]
