# Generated by Django 2.1 on 2019-02-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='sid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
