# Generated by Django 2.1 on 2019-02-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneApp', '0002_monitor_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
