# Generated by Django 2.1 on 2019-02-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneApp', '0003_monitor_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor_copy1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('major_name', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tuition_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('state_code', models.IntegerField(blank=True, null=True)),
                ('url_now', models.CharField(blank=True, max_length=255, null=True)),
                ('url_old', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitor_copy1',
                'managed': True,
            },
        ),
    ]
